Added all of my mods and Gareth48's
neos-modding-group/neos-mod-manifest pull request #104
Opened 2022-07-31 21:11 UTC by badhaloninja

Added all of my missing mods and updated ones already listed
Also added Gareth's particle workshop mod
Was putting this off for a while and finally got the motivation to do this 

Was unsure of how to handle the Discord.Net dlls for [HeadlessTweaks](https://github.com/New-Project-Final-Final-WIP/HeadlessTweaks) so I put them in the artifacts array of the releases

2022-08-18 11:42 UTC, EIA485 commented
hey, for headless tweaks add all the discord.net dlls as dependencies like in #82
i should review this as to take some load off lj but want to be fully transparent. i am not affiliated with any of these mods development but did make the old pr for headless tweaks.

2022-08-18 21:43 UTC, badhaloninja commented
There we go, I've separated the Discord.Net into their own entries
And the binaries on my releases tab are from the [nuget](https://www.nuget.org/packages/Discord.Net.Webhook/) for Discord.Net automatically downloaded via visual studio
I think you can manually download them from [nuget.info](https://nuget.info/packages/Discord.Net.Webhook/3.7.2) but I wasn't sure how or if I should directly link to those files there

2022-08-20 13:33 UTC, ljoonal requested changes
If it'd be acceptable, could we only add the artifacts only for the latest versions? As reviewing old versions adds extra work. I don't ever see a reason to add the artifacts for anything but the latest working version.

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +        },
👍

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +                "1.2.0": {
Didn't review properly, but I think we can just trust it enough to not be malicious, since didn't see anything clearly out of place.

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +        },
👍

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +        },
👍

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +        },
👍

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +        },
Uses hardcoded neosdb urls & seems windows specific, so missing broken on linux flag, or making a OS check and adding `shutdown now` when running on linux

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +        },
👍

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +            }
Didn't review old versions

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +                "1.2.1": {
👍 but Hardcodes neosdb url

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +                }
Didn't review old version

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +                },
👍

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +        },
👍

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +        },
👍

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +                }
👍 but hardcoded neosdb url

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +                }
Didn't review old version

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +                },
👍 but hardcoded neosdb url

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +        },
👍

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +                }
Didn't review old versions

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +                },
IL transpiler stuff though looks fine as it only ever removes a code instruction.

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +                },
Sha256 mashes upstream, so 👍 even though didn't review properly

2022-08-20 13:33 UTC, ljoonal commented on manifest.json
> +                },
Sha256 matches upstream so 👍

2022-08-20 14:02 UTC, badhaloninja commented
Alright, I've gotten rid of all of the non reviewed old versions
Also added linux broken flags to ExitNeosAndShutDown
And fixed the filename for Discord.Net.Webhook

2022-08-20 15:06 UTC, ljoonal commented
> parse error: Expected separator between values at line 3533, column 43

2022-08-20 15:08 UTC, ljoonal approved these changes

2022-08-20 15:09 UTC, merged