Add NeosVideoPlayerFix v4.0.0
neos-modding-group/neos-mod-manifest pull request #193
Opened 2022-12-11 14:48 UTC by Frozenreflex

2022-12-13 02:28 UTC, EIA485 commented
unless a repo has been deleted we dont remove it from the manifest, instead we add the deprecated tag. to decide on for future handling of cases like this one ive opened issue #194

2022-12-19 07:19 UTC, EIA485 requested changes

2022-12-19 07:19 UTC, EIA485 commented on manifest.json
> -        "io.github.kyuubiyoru.disablelibvlc": {
please use the deprecated flag instead of removing it from the manifest.

2022-12-19 08:10 UTC, EIA485 approved these changes

2022-12-19 20:49 UTC, ljoonal approved these changes

2022-12-19 20:49 UTC, merged