Add v1.4.0 of badhaloninja.UserJoinLeaveNotifications
neos-modding-group/neos-mod-manifest pull request #208
Opened 2023-01-07 14:04 UTC by badhaloninja

2023-01-13 17:26 UTC, ljoonal requested changes
> ❯ ./review.sh me.badhaloninja.UserJoinLeaveNotifications 1.4.0
SHA256 sums don't match!
Expected: 0837ab104cb5dc55eec21c27dc4d84cb886d5eb1acdc3a6034a598c0be288cdf
Actual:   c5029d87001b85d4cc62f120da94afe7e895ebafed04f3ebc0efd8e388c76d61

2023-01-13 17:28 UTC, EIA485 commented on manifest.json
> +                            "url": "https://github.com/badhaloninja/UserJoinLeaveNotifications/releases/download/v1.3.0/UserJoinLeaveNotifications.dll",
looks like the reason for the checksums not matching is this link being incorrect

2023-01-13 17:29 UTC, EIA485 commented on manifest.json
> +                            "url": "https://github.com/badhaloninja/UserJoinLeaveNotifications/releases/download/v1.3.0/UserJoinLeaveNotifications.dll",
https://github.com/badhaloninja/UserJoinLeaveNotifications/releases/download/v1.4.0/UserJoinLeaveNotifications.dll returns a file with the correct checksum

2023-01-14 06:34 UTC, badhaloninja commented
Oops, should be fixed now

2023-01-24 23:03 UTC, XDelta approved these changes

2023-01-24 23:08 UTC, XDelta commented
> > ❯ ./review.sh me.badhaloninja.UserJoinLeaveNotifications 1.4.0
> > SHA256 sums don't match!
> > Expected: 0837ab104cb5dc55eec21c27dc4d84cb886d5eb1acdc3a6034a598c0be288cdf
> > Actual:   c5029d87001b85d4cc62f120da94afe7e895ebafed04f3ebc0efd8e388c76d61

Github being weird and I can't seem to mark this as resolved.

2023-01-25 03:21 UTC, EIA485 commented
lj has to be the one to remove it

2023-01-25 10:55 UTC, ljoonal approved these changes

2023-01-25 10:59 UTC, merged