Update manifest.json
neos-modding-group/neos-mod-manifest pull request #94
Opened 2022-07-22 03:05 UTC by Sox-NeosVR

2022-07-22 05:41 UTC, EIA485 requested changes

2022-07-22 05:41 UTC, EIA485 commented on manifest.json
> +	"net.Sox.EasyVoiceMessage": {
indentation is wrong

2022-07-22 05:49 UTC, EIA485 commented
other notes: 
link in mod class is blank
linked artifact seems to have been built in debug mode
would be nice if the  AssemblyCompany attribute was set to author name
AssemblyCopyright attribute is a year out of date

2022-07-22 06:04 UTC, EIA485 approved these changes

2022-07-23 14:55 UTC, ljoonal approved these changes

2022-07-23 14:55 UTC, merged