added 3 of my mods
neos-modding-group/neos-mod-manifest pull request #98
Opened 2022-07-29 12:07 UTC by art0007i

2022-07-31 16:06 UTC, ljoonal approved these changes

2022-07-31 16:06 UTC, ljoonal commented on manifest.json
> +        "me.art0007i.CustonInspectors": {
Custon vs Custom ?

2022-07-31 22:22 UTC, XDelta commented on manifest.json
> +            "sourceLocation": "https://github.com/art0007i/CustonInspectors",
404 link, Custon instead of custom

2022-08-01 04:21 UTC, EIA485 commented
resolved merge conflicts

2022-08-14 23:14 UTC, ljoonal requested changes
404 links Delta pointed out should be fixed.

2022-08-17 15:41 UTC, EIA485 commented on manifest.json
> +            "sourceLocation": "https://github.com/art0007i/CustonInspectors",
name is also set too "CustonInspectors"

2022-08-21 04:37 UTC, art0007i commented
ok should be good now

2022-08-21 04:37 UTC, art0007i reviewed
.
what does this mean, I reviewed my own thing?
it still says changes requested even though I have made a change? idk how github works

2022-08-21 19:02 UTC, ljoonal approved these changes

2022-08-21 20:08 UTC, merged